spring:
  datasource:
    url: jdbc:mysql://localhost:3307/linedb
    username: user
    password: password
  flyway:
    url: jdbc:mysql://localhost:3307/linedb
    user: user
    password: password
