version: '3.1'

services:

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: linedb
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    volumes:
      - ./mysql/data:/var/lib/mysql

